### ISSUE TITLE
Echarts series 每个color可以从data中读取

### ISSUE THREAD

**Issue by ruoweiys14** [amily4555/MasterRT#158]
希望支持 Echarts 每个series的color可以从data读取

**Comment by amily4555** [comment]
这不是一个合理的需求

- 每个 series 都是通过计算而出， 它是一组 Data 的集合，每个data都有自己的属性，很难不使用规则定位需要pick出来的数据
- 每个data 的属性本身就是图表元素的配置信息，可能是一个点，一个块，它不能决定它的父级属性
