### ISSUE TITLE
radar indicator多个字段公用一组范围

### ISSUE THREAD

**Issue by ruoweiys14** [amily4555/MasterRT#2]
1）radar area 中radar.indicator=[{name:'XXX1',min:0, max: 'XXX'}，{name:'XXX2',min:0, max: 'XXX'}];
2）min为0，max取数据最大值+XX值，每个name中的min，max都一样

**Comment by amily4555** [comment]
<MrEcharts chartTypes="radar::radarZero::radarMaximum" data={dataSource.radar}/>
